export default {
    BROADCAST_DAY_LIMIT: 'BROADCAST_DAY_LIMIT',
    ACCESS_DAY_LIMIT: 'ACCESS_DAY_LIMIT',
    ACCESS_MINUTE_LIMIT: 'BROADCAST_MINUTE_LIMIT',
    BROADCAST_MINUTE_LIMIT: 'BROADCAST_DAY_LIMIT',
    INTERNET_ERROR: 'INTERNET_ERROR'
}